---
swagger: "2.0"
info:
  description: "A simple API for managing a to-do list."
  version: "1.0.0"
  title: "To-Do List API"
  contact:
    name: "Alan"
    email: "developer@example.com"
host: "localhost:5000"
basePath: "/api"
schemes:
- "http"
paths:
  /todos:
    get:
      tags:
      - "default_controller"
      summary: "Get all to-do items"
      description: "Retrieve a list of all to-do items."
      operationId: "controllers.default_controller.todos_get"
      parameters: []
      responses:
        200:
          description: "A list of to-do items"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ToDo"
    post:
      tags:
      - "default_controller"
      summary: "Create a new to-do item"
      description: "Add a new item to the to-do list."
      operationId: "controllers.default_controller.todos_post"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/NewToDo"
      responses:
        201:
          description: "To-do item created successfully"
          schema:
            $ref: "#/definitions/ToDo"
  /todos/{id}:
    get:
      tags:
      - "default_controller"
      summary: "Get a specific to-do item"
      description: "Retrieve details of a specific to-do item by its ID."
      operationId: "controllers.default_controller.todos_id_get"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "Details of the requested to-do item"
          schema:
            $ref: "#/definitions/ToDo"
        404:
          description: "To-do item not found"
    put:
      tags:
      - "default_controller"
      summary: "Update a specific to-do item"
      description: "Update details of a to-do item by its ID."
      operationId: "controllers.default_controller.todos_id_put"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/NewToDo"
      responses:
        200:
          description: "To-do item updated successfully"
          schema:
            $ref: "#/definitions/ToDo"
        404:
          description: "To-do item not found"
    delete:
      tags:
      - "default_controller"
      summary: "Delete a specific to-do item"
      description: "Remove a to-do item from the list by its ID."
      operationId: "controllers.default_controller.todos_id_delete"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
      responses:
        204:
          description: "To-do item deleted successfully"
        404:
          description: "To-do item not found"
definitions:
  ToDo:
    type: "object"
    properties:
      id:
        type: "integer"
        example: 1
      title:
        type: "string"
        example: "Buy groceries"
      description:
        type: "string"
        example: "Get milk, bread, and eggs."
      completed:
        type: "boolean"
        example: false
  NewToDo:
    type: "object"
    properties:
      title:
        type: "string"
        example: "Clean the house"
      description:
        type: "string"
        example: "Vacuum and dust all rooms."
      completed:
        type: "boolean"
        example: false
